### ISSUE TITLE
Health Estimate Syntax Error

### ISSUE THREAD

**Issue by zedsupremus** [xdy/twodsix-foundryvtt#1482]
Cross post of
https://github.com/mclemente/healthEstimate/issues/203

Health estimate

Seems to throw 
logic.js:314 SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at HealthEstimate.breakOverlayRender (logic.js:295:12)
    at addCharacter (HealthMonitor.js:34:45)
    at Array.forEach (<anonymous>)
    at Object.onCanvasReady [as fn] (hooks.js:31:10)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Canvas.draw (foundry.js:26630:11)
    at async Scene.view (foundry.js:23682:7)
    at async Game.initializeCanvas (foundry.js:8837:20)

Unfortunately my js debugging skills are.. poor and i cant quite see where the problem is, if i had to guess its something wrong here either in system identification or the constants declaration
https://github.com/mclemente/healthEstimate/blob/e54fbce610b7163d71c62bc87a09bf851ab82e64/module/EstimationProvider.js#L1501C2-L1501C2

To Reproduce
Have 2d6 system
Create actor/animal
Drop on canvas.
Inspect Console

Game Specifics (please complete the following information):

Twodsix 4.1.0 though its been happening for a long time
Health Estimate 31.6.2 though its been happening for a long time
Additional context
I -think- this began either in April or after V11. Its unclear as It was looking fine to a GM but broken for players. (And none of them mentioned it for months)

**Comment by zedsupremus** [comment]
Additional

Ships robots and space objects seem to throw slightly differently

logic.js:175 Health Estimate | Error on getEstimation(). Token Name: "Wasteful Test". Type: "ship". Error: Token's fraction is not valid, it probably doesn't have a numerical HP or Max HP value.
    at HealthEstimate.getFraction (logic.js:191:10)
    at HealthEstimate.getEstimation (logic.js:162:33)
    at HealthEstimate._handleOverlay (logic.js:63:42)
    at Object.refreshToken [as fn] (hooks.js:115:23)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Token.applyRenderFlags (foundry.js:28389:11)
    at #applyRenderFlags (foundry.js:27744:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)

logic.js:175 Health Estimate | Error on getEstimation(). Token Name: "Knowledgeable Test". Type: "robot". Error: Token's fraction is not valid, it probably doesn't have a numerical HP or Max HP value.
    at HealthEstimate.getFraction (logic.js:191:10)
    at HealthEstimate.getEstimation (logic.js:162:33)
    at HealthEstimate._handleOverlay (logic.js:63:42)
    at Object.refreshToken [as fn] (hooks.js:115:23)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Token.applyRenderFlags (foundry.js:28389:11)
    at #applyRenderFlags (foundry.js:27744:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)
    
    logic.js:175 Health Estimate | Error on getEstimation(). Token Name: "Receptive Test". Type: "space-object". Error: Token's fraction is not valid, it probably doesn't have a numerical HP or Max HP value.
    at HealthEstimate.getFraction (logic.js:191:10)
    at HealthEstimate.getEstimation (logic.js:162:33)
    at HealthEstimate._handleOverlay (logic.js:63:42)
    at Object.refreshToken [as fn] (hooks.js:115:23)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Token.applyRenderFlags (foundry.js:28389:11)
    at #applyRenderFlags (foundry.js:27744:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)

**Comment by zedsupremus** [comment]
Looks like health estimate has issued a fix AND added the new objects, tests well too.
Space-objects are supposed. though given they lack health they dont get anything but at least they dont throw errors
